= plan

* add tests based on requirements
* refactor/simplify the logic
* fix to comply with the requirements
  ** "Sulfuras*" instead of only "Sulfuras, Hand of Ragnaros"
  ** "Backstage pass*" instead of only "Backstage passes to a TAFKAL80ETC concert"
  ** "Aged*" instead of only "Aged Brie"
  ** this is something which should be normally discussed and verified with the PO or the client, thought I don't have that option in this exercise and there is clear mismatch in the requirements and the existing code.
  ** it is needed (to some extent) to support the new functionality according to the requirements and existing test for the new requirement
* add new item (if needed, it can be added at this point, before additional refactoring)
* additional refactoring
  ** categories instead of specific items?
  ** more objective approach vs update logic in one method?
* additional talking points
  ** updateQuality() can be run only once a day - it's not idempotent
  => there is no way to recover if it fails at some point
  => it's not suitable for more complicated processing with remote resources nor larger datasets (which can't be processed in-memory)

